pipeline {
    agent any

    environment {
        IMAGE_NAME = 'python-flask-app'
        CONTAINER_NAME = 'gracious_goldberg'
        PORT = '5000'
    }

    stages {

        stage('Build') {
            steps {
                echo 'Build triggered by GitHub push!'
            }
        }

        stage('Checkout') {
            steps {
                git url: 'https://github.com/kishoreg9988/assignment-4.git', branch: 'sample-py-webapp'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    cd py-flask-webapp
                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true
                    docker rmi $IMAGE_NAME || true
                    docker build -t $IMAGE_NAME .
                '''
            }
        }

        stage('Run Pytest') {
            steps {
                echo "🧪 Running tests with pytest..."
                sh '''
                    cd py-flask-webapp
                    docker run --rm $IMAGE_NAME pytest tests/
                '''
            }
        }

        stage('Deploy Flask App') {
            steps {
                sh '''
                    docker run -d -p $PORT:5000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                    sleep 3
                    curl -f http://localhost:$PORT || (echo "App not healthy!" && exit 1)
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully.'
        }
        failure {
            echo '❌ Pipeline failed. Check logs.'
        }
        always {
            sh 'docker image prune -f'
        }
    }
}

